using System.Runtime.InteropServices;

namespace PimGui.Core;

/// <summary>An opaque sRGB ARGB scheme generated by the pinned official Material Color Utilities engine.</summary>
public sealed record MonetScheme
{
    public required uint Seed { get; init; }
    public uint? SecondSeed { get; init; }
    public required bool IsDark { get; init; }
    public required string Variant { get; init; }
    public required uint Primary { get; init; }
    public required uint OnPrimary { get; init; }
    public required uint PrimaryContainer { get; init; }
    public required uint OnPrimaryContainer { get; init; }
    public required uint Secondary { get; init; }
    public required uint OnSecondary { get; init; }
    public required uint SecondaryContainer { get; init; }
    public required uint OnSecondaryContainer { get; init; }
    public required uint Tertiary { get; init; }
    public required uint OnTertiary { get; init; }
    public required uint TertiaryContainer { get; init; }
    public required uint OnTertiaryContainer { get; init; }
    public required uint Surface { get; init; }
    public required uint OnSurface { get; init; }
    public required uint SurfaceVariant { get; init; }
    public required uint OnSurfaceVariant { get; init; }
    public required uint SurfaceDim { get; init; }
    public required uint SurfaceBright { get; init; }
    public required uint SurfaceContainerLowest { get; init; }
    public required uint SurfaceContainerLow { get; init; }
    public required uint SurfaceContainer { get; init; }
    public required uint SurfaceContainerHigh { get; init; }
    public required uint SurfaceContainerHighest { get; init; }
    public required uint Outline { get; init; }
    public required uint OutlineVariant { get; init; }
    public required uint Error { get; init; }
    public required uint OnError { get; init; }
    public required uint ErrorContainer { get; init; }
    public required uint OnErrorContainer { get; init; }
    public required uint InverseSurface { get; init; }
    public required uint InverseOnSurface { get; init; }
    public required uint InversePrimary { get; init; }
    public required uint SurfaceTint { get; init; }
    public required uint Background { get; init; }
    public required uint OnBackground { get; init; }
    public required uint Shadow { get; init; }
    public required uint Scrim { get; init; }
    public required uint PrimaryFixed { get; init; }
    public required uint PrimaryFixedDim { get; init; }
    public required uint OnPrimaryFixed { get; init; }
    public required uint OnPrimaryFixedVariant { get; init; }
    public required uint SecondaryFixed { get; init; }
    public required uint SecondaryFixedDim { get; init; }
    public required uint OnSecondaryFixed { get; init; }
    public required uint OnSecondaryFixedVariant { get; init; }
    public required uint TertiaryFixed { get; init; }
    public required uint TertiaryFixedDim { get; init; }
    public required uint OnTertiaryFixed { get; init; }
    public required uint OnTertiaryFixedVariant { get; init; }
}

/// <summary>The genuine native color engine could not be loaded; callers must retain their last valid scheme.</summary>
public sealed class MonetEngineUnavailableException(string message, Exception? innerException = null)
    : InvalidOperationException(message, innerException) { }

/// <summary>
/// ABI adapter only: color quantization, AOSP seed scoring, HCT and dynamic roles live in the
/// pinned native engine. There is deliberately no RGB/HSL or hardcoded replacement palette.
/// </summary>
public static class MonetColors
{
    public const int MaximumPixelCount = 12544;
    public const int CacheCapacity = 64;
    private const int RoleCount = 49;
    private const string Library = "PyDeck.Colors.dll";
    private static readonly object Gate = new();
    private readonly record struct SchemeKey(uint Seed, uint SecondSeed, bool Dark, int Variant);
    private sealed record CacheEntry(SchemeKey Key, MonetScheme Scheme);
    private static readonly Dictionary<SchemeKey, LinkedListNode<CacheEntry>> Cache = new();
    private static readonly LinkedList<CacheEntry> Recency = new();
    private static string? engineVersion;

    public static int CachedSchemeCount { get { lock (Gate) return Cache.Count; } }

    public static string EngineVersion
    {
        get
        {
            lock (Gate)
            {
                if (engineVersion is not null) return engineVersion;
                try
                {
                    var result = Marshal.PtrToStringUTF8(NativeVersion());
                    if (string.IsNullOrWhiteSpace(result)) throw new MonetEngineUnavailableException("The Material color engine returned no version information.");
                    return engineVersion = result;
                }
                catch (Exception ex) when (IsLoadFailure(ex)) { throw Unavailable(ex); }
            }
        }
    }

    public static uint SeedFromPixels(uint[] argb)
    {
        ArgumentNullException.ThrowIfNull(argb);
        if (argb.Length > MaximumPixelCount)
            throw new ArgumentOutOfRangeException(nameof(argb), $"Supply no more than {MaximumPixelCount} sRGB ARGB pixels.");
        try
        {
            var status = NativeSeed(argb, (uint)argb.Length, out var seed);
            CheckStatus(status, "extract a wallpaper seed");
            return seed | 0xFF000000u;
        }
        catch (Exception ex) when (IsLoadFailure(ex)) { throw Unavailable(ex); }
    }

    public static uint[] SeedsFromPixels(uint[] argb)
    {
        ArgumentNullException.ThrowIfNull(argb);
        if (argb.Length > MaximumPixelCount)
            throw new ArgumentOutOfRangeException(nameof(argb), $"Supply no more than {MaximumPixelCount} sRGB ARGB pixels.");
        var seeds = new uint[4];
        try
        {
            CheckStatus(NativeSeeds(argb, (uint)argb.Length, seeds, (uint)seeds.Length, out var count), "extract wallpaper seed candidates");
            if (count is < 1 or > 4 || seeds.Take((int)count).Any(color => (color >> 24) != 255))
                throw new InvalidOperationException("The Material color engine returned invalid wallpaper seed candidates.");
            return seeds[..(int)count];
        }
        catch (Exception ex) when (IsLoadFailure(ex)) { throw Unavailable(ex); }
    }

    public static MonetScheme Create(uint seed, bool dark, string variant = "TonalSpot", uint? secondSeed = null)
    {
        var variantId = variant switch
        {
            "TonalSpot" => 0,
            "Expressive" => 1,
            "DualSource" => 2,
            _ => throw new ArgumentException("The supported Material color variants are TonalSpot, Expressive and DualSource.", nameof(variant))
        };
        seed |= 0xFF000000u;
        var effectiveSecondSeed = variantId == 2 ? (secondSeed ?? seed) | 0xFF000000u : 0u;
        var key = new SchemeKey(seed, effectiveSecondSeed, dark, variantId);
        lock (Gate)
        {
            if (Cache.TryGetValue(key, out var cached))
            {
                Recency.Remove(cached); Recency.AddLast(cached);
                return cached.Value.Scheme;
            }
            var roles = new uint[RoleCount];
            try { CheckStatus(variantId == 2 ? NativeDualScheme(seed, effectiveSecondSeed, dark ? 1 : 0, roles, RoleCount)
                : NativeScheme(seed, dark ? 1 : 0, variantId, roles, RoleCount), "generate a Material color scheme"); }
            catch (Exception ex) when (IsLoadFailure(ex)) { throw Unavailable(ex); }
            if (roles.Any(color => (color & 0xFF000000u) != 0xFF000000u))
                throw new InvalidOperationException("The Material color engine returned an invalid role buffer. The previous valid palette has been retained.");
            var scheme = new MonetScheme
            {
                Seed = seed, SecondSeed = variantId == 2 ? effectiveSecondSeed : null, IsDark = dark, Variant = variant,
                Primary = roles[0], OnPrimary = roles[1], PrimaryContainer = roles[2], OnPrimaryContainer = roles[3],
                Secondary = roles[4], OnSecondary = roles[5], SecondaryContainer = roles[6], OnSecondaryContainer = roles[7],
                Tertiary = roles[8], OnTertiary = roles[9], TertiaryContainer = roles[10], OnTertiaryContainer = roles[11],
                Surface = roles[12], OnSurface = roles[13], SurfaceVariant = roles[14], OnSurfaceVariant = roles[15],
                SurfaceDim = roles[16], SurfaceBright = roles[17], SurfaceContainerLowest = roles[18], SurfaceContainerLow = roles[19],
                SurfaceContainer = roles[20], SurfaceContainerHigh = roles[21], SurfaceContainerHighest = roles[22],
                Outline = roles[23], OutlineVariant = roles[24], Error = roles[25], OnError = roles[26],
                ErrorContainer = roles[27], OnErrorContainer = roles[28], InverseSurface = roles[29], InverseOnSurface = roles[30],
                InversePrimary = roles[31], SurfaceTint = roles[32], Background = roles[33], OnBackground = roles[34],
                Shadow = roles[35], Scrim = roles[36], PrimaryFixed = roles[37], PrimaryFixedDim = roles[38],
                OnPrimaryFixed = roles[39], OnPrimaryFixedVariant = roles[40], SecondaryFixed = roles[41], SecondaryFixedDim = roles[42],
                OnSecondaryFixed = roles[43], OnSecondaryFixedVariant = roles[44], TertiaryFixed = roles[45], TertiaryFixedDim = roles[46],
                OnTertiaryFixed = roles[47], OnTertiaryFixedVariant = roles[48]
            };
            // Publish only complete successful results. Failed native calls never evict a valid entry.
            var node = Recency.AddLast(new CacheEntry(key, scheme));
            Cache.Add(key, node);
            if (Cache.Count > CacheCapacity && Recency.First is { } oldest)
            {
                Recency.RemoveFirst(); Cache.Remove(oldest.Value.Key);
            }
            return scheme;
        }
    }

    public static void ClearCache() { lock (Gate) { Cache.Clear(); Recency.Clear(); } }

    private static bool IsLoadFailure(Exception ex) => ex is DllNotFoundException or EntryPointNotFoundException or BadImageFormatException;
    private static MonetEngineUnavailableException Unavailable(Exception ex) => new(
        "The official Material color engine (PyDeck.Colors.dll) is unavailable or incompatible. Restore the application files; the previous valid palette has been retained.", ex);
    private static void CheckStatus(int status, string action)
    {
        if (status != 0) throw new InvalidOperationException($"The Material color engine could not {action} (native status {status}). The previous valid palette has been retained.");
    }

    [DllImport(Library, EntryPoint = "PyDeckColorsSeed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [DefaultDllImportSearchPaths(DllImportSearchPath.AssemblyDirectory | DllImportSearchPath.SafeDirectories)]
    private static extern int NativeSeed([In] uint[] pixels, uint count, out uint seed);
    [DllImport(Library, EntryPoint = "PyDeckColorsSeeds", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [DefaultDllImportSearchPaths(DllImportSearchPath.AssemblyDirectory | DllImportSearchPath.SafeDirectories)]
    private static extern int NativeSeeds([In] uint[] pixels, uint count, [Out] uint[] seeds, uint capacity, out uint written);
    [DllImport(Library, EntryPoint = "PyDeckColorsDualScheme", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [DefaultDllImportSearchPaths(DllImportSearchPath.AssemblyDirectory | DllImportSearchPath.SafeDirectories)]
    private static extern int NativeDualScheme(uint seed, uint secondSeed, int dark, [Out] uint[] roles, uint roleCount);
    [DllImport(Library, EntryPoint = "PyDeckColorsScheme", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [DefaultDllImportSearchPaths(DllImportSearchPath.AssemblyDirectory | DllImportSearchPath.SafeDirectories)]
    private static extern int NativeScheme(uint seed, int dark, int variant, [Out] uint[] roles, uint roleCount);
    [DllImport(Library, EntryPoint = "PyDeckColorsVersion", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [DefaultDllImportSearchPaths(DllImportSearchPath.AssemblyDirectory | DllImportSearchPath.SafeDirectories)]
    private static extern IntPtr NativeVersion();
}
